name: Build and push Docker images

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      builder-name: ${{ steps.buildx.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

  build-and-push:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push GPU image (multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ritikvirus/comfyui-runpod:latest

      - name: Build and push CPU image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cpu
          platforms: linux/amd64
          push: true
          tags: |
            ritikvirus/comfyui-runpod:cpu-latest
